act_fn: silu
autoregressive_prior: false
batch_size: 512
beta_classifier: 2.0
beta_mi_estimator: 2.0
beta_t1: 1.0
c_hid: 32
c_in: 4
causal_encoder_checkpoint: null
classifier_act_fn: silu
classifier_gumbel_temperature: 1.0
classifier_lr: 0.004
classifier_momentum: 0.0
classifier_num_layers: 1
classifier_use_conditional_targets: false
classifier_use_normalization: false
cluster_logging: false
coarse_vars: false
data_folder: interventional_pong
data_img_width: -1
decoder_num_blocks: 1
exclude_objects: null
exclude_vars: null
gamma: 1.0
graph_learning_method: ENCO
img_width: 32
imperfect_interventions: false
kld_warmup: 0
lambda_reg: 0.0
lambda_sparse: 0.02
lr: 0.001
max_iters: 39000
mi_estimator_comparisons: 1
no_encoder_decoder: false
num_causal_vars: 5
num_latents: 16
num_workers: 4
seq_len: 2
use_flow_prior: true
var_names:
- ball-vel-dir
- ball-x
- ball-y
- paddle-left-y
- paddle-right-y
warmup: 100
